# Generated by Django 3.1.6 on 2021-02-15 17:21

from django.db import migrations, models
import django_editorjs.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_editorjs.fields.EditorJsField(),
        ),
    ]
