# Generated by Django 3.1.6 on 2021-02-15 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210215_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_published',
            new_name='published',
        ),
    ]
