# Generated by Django 3.1.6 on 2021-02-15 17:50

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210215_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=datetime.datetime(2021, 2, 15, 17, 50, 3, 888979, tzinfo=utc), editable=False, populate_from='title', unique_with=['pub_date__month']),
            preserve_default=False,
        ),
    ]
